; ALLOWS ONE TO START THE APPLICATION WITH RUN
; SYS 2064
*=$0801 
         BYTE $0C, $8, $0A, $00, $9E, $20, $32, $30, $36, $34, $00, $00, $00, $00, $00

; MEMORY POINTERS
IRQFLAG    = $D019
IRQCTRL    = $D01A
IRQADDRMSB = $0314
IRQADDRLSB = $0315
IRQRASTER  = $D012
CIA1IRQ    = $DC0D
RASTERREG  = $D011

; KERNAL ROUTINES
IRQCONTINUE     = $EA81
IRQFINISH       = $EA31


; TODO HERE BE SPRITES
; SCREEN WILL BE DIVIDED 3 VERTICAL PORTIONS, AND EACH OF THEM WILL DISPLAY SPRITES

INIT    
        LDA #%01111111 ; SWITCH OFF CIA-1 INTERRUPTS
        STA CIA1IRQ

        AND $D011 ; CLEAR VIC RASTER REGISTER
        STA RASTERREG

        LDA #0 ; START WITH IRQ0 AT RASTER LINE 0
        STA IRQRASTER
        LDA #<IRQ0
        STA IRQADDRMSB
        LDA #>IRQ0
        STA IRQADDRLSB

        LDA #%00000001 ; ENABLE RASTER INTERRUPTS ONLY AFTER SETUP
        STA IRQCTRL

MAIN    
        JMP MAIN

IRQ0    
        ; TODO

        LDA #104 ; NEXT DO IRQ1 AT RASTER LINE 104
        STA IRQRASTER
        LDA #<IRQ1
        STA IRQADDRMSB
        LDA #>IRQ1
        STA IRQADDRLSB

        ASL IRQFLAG ; RESET IRQ FLAG

        JMP IRQCONTINUE ; CONTINUE WITH IRQS

IRQ1    
        ; TODO

        LDA #208 ; NEXT TO IRQ2 AT RASTER LINE 208
        STA IRQRASTER
        LDA #<IRQ2
        STA IRQADDRMSB
        LDA #>IRQ2
        STA IRQADDRLSB

        ASL IRQFLAG

        JMP IRQCONTINUE

IRQ2    
        ; TODO

        LDA #0 ; START AGAIN WITH IRQ0
        STA IRQRASTER
        LDA #<IRQ0
        STA IRQADDRMSB
        LDA #>IRQ0
        STA IRQADDRLSB

        ASL IRQFLAG

        JMP IRQFINISH ; LET MACHINE HANDLE OTHER IRQS